### ISSUE TITLE
Please add an option to specify a location for storing the config files of dgenies

### ISSUE THREAD

**Issue by samfux84** [genotoul-bioinfo/dgenies#1]
Hi,

The INSTALL.md file states:

```
Configuration file location:

Linux:
/etc/dgenies/application.properties if installed with root access
~/.dgenies/application.properties else
```

On HPC clusters, it is very common to install software centrally in user space (and therefore not to install it as root). Due to security reasons (the cluster is shared by 3000 users), we cannot allow software to install files in /var or /etc. But on the other hand, it is also not very suitable to have the config file in the users home, as I would like to do a central installation in a location like

/cluster/apps/python/3.6.1

such that all users can use the software.

Would it be possible to add an option to specify a path, where the config files are stored ?

Which locations in the code would I need to change to set another path for storing the configuration files ?

**Computer (please complete the following information):**
 - OS: CentOS Linux release 7.4.1708 (Core)

**Comment by samfux84** [comment]
Are the config files even required in standalone mode ? Or can I just remove the following section from setup.py:

```
    config_dir = '/etc/dgenies'
    wsgi_dir = '/var/www/dgenies'
    if '--user' in sys.argv:
        config_dir = os.path.join(str(Path.home()), ".dgenies")
        wsgi_dir = config_dir
```

**Comment by florealcab** [comment]
I don't really fully understand your problem.

You want to install D-Genies globally on your cluster and then each user should launch it? Please note that D-Genies is NOT a command line tool. It launch on a web port (even in standalone mode, with 5000 port by default). So, each user should launch it in a different port, I suppose you know that?

We think the best practice is to install D-Genies on a web machine (a VM for example) which have access to your cluster. Then, D-Genies will submit jobs on it and the web interface is shared. So, no port problem.

But, I will answer your question.

You have two choices

First one: without editing the code
---------------------------

Just edit the setup.py file and remove this line (35):

> data_files=data_files,

Then, copy application.properties file in the D-Genies install dir (inside the dgenies folder of the site-packages dir of python), and rename it "application-dev.properties". We use it for development but it will work also in production

Second one: change file path in the code
----------------------------

Edit the file "src/dgenies/config_reader.py" before install and add your path to the desired file path inside the __init__ function, just after those files:

     config_file.append(os.path.join(self.app_dir, "application-dev.properties"))
     config_file.append(os.path.join(self.app_dir, "application-dev.properties.local"))
     **config_file.append("/path/to/your/application.properties")**

Edit the setup.py and change the config_dir to the full path which is suppose to contain the application.properties file. You can set wsgi_dir to whatever you want (not used in standalone mode).

Then, run setup for install.

Don't hesitate tell us if you have some issues or some questions about that.

**Comment by samfux84** [comment]
@florealcab: Thank you for your reply and for explaining me how dgenies is supposed to be setup. I think in this regard, it does not make sense to install the software on our HPC cluster. I will tell the user that requested the installation of this Python package to look for a different solution as we are only managing HPC clusters and do not provide VM's.
