### ISSUE TITLE
D-Genies webpage back date 

### ISSUE THREAD

**Issue by xbwdk** [genotoul-bioinfo/dgenies#105]
Dear Developers,

I saw the D-Genies webpage is under maintenance for a while, may I ask approximately when it will be back, please?
I really like your package, but I got some problems with running the standalone version on my server, so I am heavily relying on the web page.

Best wishes,
xbwdk

**Comment by Bios4Biol** [comment]
Hi xbwdk,

We are really sorry for this situation and our system administrators are doing their best to restore the service but several disks have stopped working at the same time putting the volume in failure state and their are currently trying to restore it without data loss.

Cheers,

**Comment by pbordron** [comment]
See #96 for update
