### ISSUE TITLE
Command-Line

### ISSUE THREAD

**Issue by fjruizruano** [genotoul-bioinfo/dgenies#11]
Hi @genotoul-bioinfo,

I would like to know if it is possible to run dgenies using only the Linux command-line.

Thanks in advance,
Francisco.

**Comment by chklopp** [comment]
Hi,

The image rendering is performed by your WEB-browser therefore it is not possible to run all the process using a command line.
You can produce the alignment and index files using command lines and then only produce the dotplot with d-genies with the 'plot alignment' options.

**Comment by fjruizruano** [comment]
Thanks, @chklopp ! It's helpful.
Bests.
