### ISSUE TITLE
Issue running dgenies locally

### ISSUE THREAD

**Issue by SwenDiepstraten** [genotoul-bioinfo/dgenies#111]
Hello, each time I try to run dgenies via WSL I encounter the following error: [2023-11-22 14:23:23,736] ERROR in job_manager: MLNtK_20231122141703 - Run align: Failed - DGeniesRunError

I had no problem installing the packages, but whenever I start dgenies via "Dgenies run" I do get the following warnings:

[2023-11-22 14:26:15,379] INFO in _internal: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
[2023-11-22 14:26:15,379] INFO in _internal: Press CTRL+C to quit
[2023-11-22 14:26:16,403] INFO in _internal: 127.0.0.1 - - [22/Nov/2023 14:26:16] "GET / HTTP/1.1" 200 -
/home/swendiep/anaconda3/envs/dgenies/bin/dgenies:169: DeprecationWarning: 'got_first_request' is deprecated and will be removed in Flask 2.4.
  if app.got_first_request:
Starting browser...
gio: http://127.0.0.1:5000: Operation not supported

Hope you can help!

**Comment by pbordron** [comment]
Hi SwenDiepstraten

We didn't test the WSL installation, we supposed it works because it is Linux. Look like it wasn't the case. Let me investigate the case.

The `WARNING: This is a development server` is expected . The `gio: http://127.0.0.1:5000/: Operation not supported` is also something expected as the Linux subsystem cannot open the Windows web browser.

Regards

Philippe

**Comment by pbordron** [comment]
I did a test with WSL release of Ubuntu 22.04 on Windows 10. I used miniconda linux. Everything work correctly

Could you:
- give me the size of files you want to compare?
- give me more logs: 
  - the content of `~/.dgenies/data/MLNtK_20231122141703/logs.txt`
- run an align job with following files with minimap2:
  - http://ftp.ensemblgenomes.org/pub/bacteria/release-52/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655_gca_000005845/dna/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.dna.toplevel.fa.gz
  - http://ftp.ensemblgenomes.org/pub/bacteria/release-52/fasta/bacteria_79_collection/escherichia_coli_str_k_12_substr_w3110_gca_000010245/dna/Escherichia_coli_str_k_12_substr_w3110_gca_000010245.ASM1024v1.dna.toplevel.fa.gz

**Comment by SwenDiepstraten** [comment]
Hello,

The files I want to compare are both approximately 700MB.
The log is as follows:
Prepare files
Run Minimap2 v2.24 (minimap2):
/home/swendiep/anaconda3/envs/dgenies/lib/python3.12/site-packages/dgenies/bin/minimap2 -t 4 -f 0.02 -o /home/swendiep/.dgenies/data/MLNtK_20231122141703/map_raw.paf /home/swendiep/.dgenies/data/MLNtK_20231122141703/target_Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.gz /home/swendiep/.dgenies/data/MLNtK_20231122141703/split_query_snakemake_bed_scaffolds_final.fa
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~


When running the files you submitted it all works fine.

I hope this helps

-Swen

**Comment by pbordron** [comment]
Look like it is a RAM usage issue as dgenies run correctly with small files.

`Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.gz` is ~700 MB compressed / 2.4GB uncompressed.

In original dgenies paper, the align part consumes around 27 GB of RAM when comparing Cow (2.5 GB uncompressed) and Sheep (2.6GB uncompressed).

You need to run dgenies on a computer with more RAM, target at least 32 GB regarding data from original paper.
