### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by lijuan1114** [genotoul-bioinfo/dgenies#127]
**Describe the bug**
The job is always in the preparing state.

**To Reproduce**

1. Go to 'Run'
2. Upload the sequence and click on 'submit'
3. See error

**Expected behavior**
The job is always in the preparing state.

**Computer (please complete the following information):**
 - OS: linux and windows (I tried them all)
 - Browser: microsoft edge and firefox
 - Version: the latest

**Comment by pbordron** [comment]
I have restarted the service. Please try again
