### ISSUE TITLE
Can't link the website of dgenies

### ISSUE THREAD

**Issue by hungweichen0327** [genotoul-bioinfo/dgenies#20]
**Describe the bug**
I found the website of the dgenies can't be connected (http://dgenies.toulouse.inra.fr/install).
I can't find any other place to read the manual. Can you check the website? Thank you!

**Comment by chklopp** [comment]
Hi,

The website is in maintenance today and should be back online tomorrow.
The documentation can be found at https://dgenies.readthedocs.io/en/latest/
