### ISSUE TITLE
"Job does not exists!" after submission

### ISSUE THREAD

**Issue by maximilianpress** [genotoul-bioinfo/dgenies#23]
**Describe the bug**
After starting the job and uploading the files, the refreshing job page says "This job does not exists!". It continues refreshing but no progress information is displayed and it does not appear to be doing anything. 

**To Reproduce**
I am not sure how to reproduce the bug per se. I installed dgenies via conda i.e.

```
conda create -n dgenies -c bioconda dgenies
```
I had to manually edit the `application.properties` file to allow a larger file size, as it suggests in one issue. 
I then run `dgenies run` to start the server. After this, the browser window pops up and I select my files, which are uploaded (green progress bar shows upload). I used minimap2 default.

Then I get the page saying that the job does not exist.

**Expected behavior**
I expect the job to exist/complete after submission.

**Screenshots**
![image](https://user-images.githubusercontent.com/14287167/118054254-cc2e6600-b33a-11eb-9b6d-3d45a5af7ba7.png)

**Computer (please complete the following information):**
 - OS: Mac OSX 10.15.7
 - Browser  chrome 90.0.4430.85
 - Version 1.2.0 (conda)

**Additional context**
I am uploading a gzipped hg38.fa.gz, and comparing it to a large gzipped fully diploid human assembly.

It's possible that too large of a file will break dgenies? I cannot see what is going on under the hood, I am not sure where there is e.g. logging to check.

**Comment by chklopp** [comment]
dgenies should run a minimap2 alignment job on the local computer or on the computing cluster depending on your settings. This job will require over 128Gb of RAM for human genomes. You could try to use mashmap to reduce memory consumption. If it does not run on your server you can also produce the paf and idx files locally and then only print the dot plot using the 'plot alignment' section of http://dgenies.toulouse.inra.fr/run . This is explained in http://dgenies.toulouse.inra.fr/documentation/run.

**Comment by maximilianpress** [comment]
THanks, I will try this.
