### ISSUE TITLE
An unexpected error has occurred on upload

### ISSUE THREAD

**Issue by StevenBai97** [genotoul-bioinfo/dgenies#24]
Hello,
When I used the online D-GENIES, an unexpected error has occurred on upload. And then, it showed "Please contact the support".

**Comment by chklopp** [comment]
Could you please give me the job ID?

**Comment by StevenBai97** [comment]
> Could you please give me the job ID?

dQzIz_20210525155959

**Comment by chklopp** [comment]
This job does not exist in the dgenies database or data directory.
It could be a network issue.
Could you retry?

**Comment by StevenBai97** [comment]
> This job does not exist in the dgenies database or data directory.
> It could be a network issue.
> Could you retry?

Wow. It works. Thanks a lot.
