### ISSUE TITLE
Error while running dgenies

### ISSUE THREAD

**Issue by avneeshbt** [genotoul-bioinfo/dgenies#3]
While running dgenies by using command `dgenies run` I am getting following output:

No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
No section: 'global'
Traceback (most recent call last):
  File "/usr/local/bin/dgenies", line 341, in <module>
    run(*args)
  File "/usr/local/bin/dgenies", line 171, in run
    app = launch(mode=mode, debug=debug)
  File "/usr/local/lib/python3.6/dist-packages/dgenies/__init__.py", line 40, in launch
    UPLOAD_FOLDER = config_reader.upload_folder
AttributeError: 'AppConfigReader' object has no attribute 'upload_folder'

 - OS: Linux (Lubuntu)
 - Browser firefox

**Comment by dwinter** [comment]
I ran into this problem today also (from a pip install of dgenies on ubuntu 17.10), it seems the default configuration files were not installed (or at least not being found by dgenies). 

The workaround was to create a `~/.degenies` directory and  download `application.properties` and `tools.yaml` from the root of this repo. Works great after that (thanks devs for a great tool!).

**Comment by avneeshbt** [comment]
@dwinter @florealcab Thanks a lot for your help. It worked for me too.

**Comment by charles5perrier** [comment]
I have the exact same issue on my Mac and I don't manage to fix it. Has it been fixed somewhere? Or can you provide a bit more detail on how to fix it? Thanks

**Comment by Adamtaranto** [comment]
Also having this issue with dgenies installed from bioconda
