### ISSUE TITLE
Question: D-GENIES settings for minimap2 and mashmap

### ISSUE THREAD

**Issue by cabbagesofdoom** [genotoul-bioinfo/dgenies#31]
Hi,

Thanks for the really useful tool. Apologies if I have missed this somewhere obvious, but can you let me know what settings you use within D-GENIES for the `minimap2` and `mashmap` searches? I would like to pre-generate the PAF files to upload, but want to make sure that the results will be consistent with uploading the assemblies directly.

Many thanks,

Rich

**Comment by pbordron** [comment]
Hi Rich,

You can find (and configure) parameters for `minimap2` and `mashmap` in the file [`tools.yaml`](https://github.com/genotoul-bioinfo/dgenies/blob/master/tools.yaml).
The parameters set in this`tools.yaml` are the ones used on the [genotoul instance](http://dgenies.toulouse.inra.fr/).

Keep in mind that the current version of dgenies (1.2.0) is provided with `minimap2 2.11` and `mashmap2`. Results may change if you use different versions.

Regards

Philippe

**Comment by pbordron** [comment]
Let me correct something about the version used on [genotoul instance](http://dgenies.toulouse.inrae.fr/)

The version of minimap2 used is the version 2.5-r572
I will look for update it to version 2.11 to be sync with source

Regards

Philippe

**Comment by pbordron** [comment]
[Genotoul instance](http://dgenies.toulouse.inra.fr/) is now updated to last minimap2 version (2.23-r1111)
