### ISSUE TITLE
Website is possibly down

### ISSUE THREAD

**Issue by DustinSokolowski** [genotoul-bioinfo/dgenies#33]
Hello!

Thank you for the great tool. I've been using D-Genies to help visualize _de novo_ genomes and it looks like the website may be down. I haven't been able to access it for a week or so and have reset my system/used other peoples computers. I was able to use the website and view results as of this past August. Is the website still maintained?

Thanks!
Dustin

**Comment by chklopp** [comment]
Hi,

Sorry for the inconvenience. The server harboring d-genies has been on maintenance since last Sunday afternoon and until to night. We will do our best to have d-genies up again as soon as possible.

Cheers
Christophe

**Comment by DustinSokolowski** [comment]
Looks like that was it. The server is back up, Thank you!
