### ISSUE TITLE
Plot alignment doesn't specify required file suffix .idx

### ISSUE THREAD

**Issue by conchoecia** [genotoul-bioinfo/dgenies#40]
If I try to "plot alignment" on the d-genies website, I select a .paf file to use and it works fine.

I generate an index file using the python3 script on that page, works great. I name that file `xyz.index`. I upload `xyz.index` to target file or query file, I get an error `File xyz.index is not supported!`.

I downloaded the results of your example and saw that you name the indices `.idx`. I renamed `xyz.indez` to `xyz.idx` and then it worked.

Would you consider specifying on this page [http://dgenies.toulouse.inra.fr/run](http://dgenies.toulouse.inra.fr/run) that the index file must be named `.idx` to work with your tool? That might help someone like me in the future.

Thank you for writing and maintaining D-Genies!

**Comment by chklopp** [comment]
Hi,

Thank you for using d-genies.
In the run documentation http://dgenies.toulouse.inra.fr/documentation/run there is a list with possible allowed file extensions

**Allowed extensions:**
Fasta: fa, fasta, fna, fa.gz, fasta.gz, fna.gz
Index: idx

But I agree we could be more explicit in the upload section of the interface.

**Comment by pbordron** [comment]
Add to dev branch
