### ISSUE TITLE
What does repeatedness  mean? 

### ISSUE THREAD

**Issue by Nonodayo** [genotoul-bioinfo/dgenies#48]
I tried using D-genies from the following URL.
https://dgenies.toulouse.inra.fr/run

In option section,
I can select 3 mode.
"Few repeats"
"Some repeats"
"Many repeats"

What is the difference between the above three? The results are slightly different for the three?

**Comment by chklopp** [comment]
If you mouse over the question mark in front of each option you will see that it changes the -f parameter value from 0.0002 to 0.02. The larger the value the less memory and CPU time are used for the minimap2 alignment. You have examples at the bottom of the gallery page.

**Comment by Nonodayo** [comment]
Thank you very much!
