### ISSUE TITLE
Dgenies identity percentage bug? 

### ISSUE THREAD

**Issue by aderzelle** [genotoul-bioinfo/dgenies#5]
Hello again,

How does Dgenies compute identity percentage? 
I have a PAF file between 2 draft assemblies, with an average identity of 97%. However, in Dgenies, the dot plot shows up in yellow, as if the identity was between 0 and 25%. I did not find anything special with that particular PAF file produced by minimap2. It looks perfectly standard.

I can provide the PAF file if requested.
I am on Ubuntu 18.04.

Thank you, and thanks for Dgenies it's really useful to have such an easy way of doing dotplots.

**Comment by florealcab** [comment]
Identity percentage is computed using the informations given in the PAF file:
number of matching bases in the mapping (column 10) / number bases, including gaps, in the mapping (column 11).

If you're agree with that but you still have problem with your file, I can take a look to your PAF file if you send me it.

Thank you for your interest on D-Genies

**Comment by aderzelle** [comment]
This is exactly what I needed and it makes sense with my paf file. 
Thanks!
