### ISSUE TITLE
Regarding running time takes to  generate the dot plot 

### ISSUE THREAD

**Issue by Upendra19993** [genotoul-bioinfo/dgenies#53]
I want to run a dot plot in D-Genies. But, when I submit the job, it prepares the sequences for long time and does not progress further. I have obtained output earlier within 2 mins. But now, it does not show a progress at all.  Kindly advise possible reasons for this and how to resolve this.

**Comment by Upendra19993** [comment]
I want to run a dot plot in D-Genies. But, when I submit the job, it prepares the sequences for long time and does not progress further. I have obtained output earlier within 2 mins. But now, it does not show a progress at all.  Kindly advise possible reasons for this and how to resolve this.

**Comment by chklopp** [comment]
Hi,
Thank you for using dgenies.
The webserver clock was unsynchronized and therefore the jobs did not start on our cluster.
This has been fixed and works OK now.
Can you retry?

**Comment by pbordron** [comment]
Forgot to close
