### ISSUE TITLE
Launch map analysis dispay on standalone version

### ISSUE THREAD

**Issue by jeramiahsmith** [genotoul-bioinfo/dgenies#59]
I upgraded dgenies and the tabs for plot alignment, etc don't show the tabs for uploading files as before. 

<img width="963" alt="Screenshot 2023-09-01 at 4 41 48 PM" src="https://github.com/genotoul-bioinfo/dgenies/assets/48733939/e6a9e0b2-5f53-4a97-be87-34c987171a56">

**Comment by jeramiahsmith** [comment]
running this on a Mac using firefox browser

**Comment by pbordron** [comment]
After upgrading dgenies to the last version, you need to force refresh the page in order to load new versions of libraries.

You can do it with the by pressing the <kbd>⇧ Shift</kbd> key while refreshing the page (e.g. <kbd>⇧ Shift</kbd> + <kbd>⌘ Cmd</kbd> + <kbd>R</kbd>)

**Comment by jeramiahsmith** [comment]
Thanks ... works great
