### ISSUE TITLE
Dgenies with command

### ISSUE THREAD

**Issue by bijendrabio** [genotoul-bioinfo/dgenies#60]
Hello, 
Is it possible to run dgenies locally and generate plots using the command line?

Kindly suggest!

**Comment by chklopp** [comment]
Hi,

Dot plot rendering is performed by your browser therefore it is not possible in this version to use the command line to generate plots. 
If you want to generate multiple plots in one go you can use the batch mode and specify up to ten alignments or plots on our public website or as many as you want on your private installation.

Kind regards,

Christophe

**Comment by bijendrabio** [comment]
Hello Christophe, 
Thanks for your response. Also, I wonder if its able to handle large size genomes (>5Gbs). I noticed there is a size limit of 3.4Gb while using the browser. Kindly suggest!

Regards,
B

**Comment by chklopp** [comment]
Hi,

We have set this limit on the public instance because of computational limits, but you can change it in the properties file if you install dgenies on your own server or cluster. 

https://github.com/genotoul-bioinfo/dgenies/blob/master/application.properties
max_upload_size = 3G

Kind regards,

Christophe

**Comment by DustinSokolowski** [comment]
Hello!

As a quick follow-up here, Is it possible to use the scripts within d-genies to create the "association table" that gets printed out? I find the netting to be quite helpful when comparing assemblies within the same species. Alternatively if you can point me to the script responsible for this I can take the key lines and write a paf-to-assoc.py script which should work as well.

Best!
Dustin

**Comment by pbordron** [comment]
Hi Dustin,

The part creating the association table in not a part of the scripts, but is tied to the [server itself](https://github.com/genotoul-bioinfo/dgenies/blob/v1.5.0/src/dgenies/views.py#L1028-L1050) 

If you have an already computed `paf` file and [index](https://raw.githubusercontent.com/genotoul-bioinfo/dgenies/v1.5.0/src/dgenies/bin/index.py) of target and query, you can install dgenies and try to use it this way:

```python
from dgenies.lib.paf import Paf

paf_file = "map.paf" # a minimap2 alignment file
idx1 = "query.idx" # the index of query file
idx2 = "target.idx" # the index of target file

paf = Paf(paf_file, idx1, idx2, False)
paf.parse_paf(False)

csv_content = paf.build_query_on_target_association_file()
```

I didn't checked if some other files are required to create the association table.

**Comment by DustinSokolowski** [comment]
This is great, thank you.

Best,
Dustin
