### ISSUE TITLE
Max identity feature/multiple alignment display

### ISSUE THREAD

**Issue by rotifergirl** [genotoul-bioinfo/dgenies#7]
I am aligning a genome assembly to itself to identify regions which have been repeated, and I know a large portion of my assembly is duplicated and has around 80-90% identity, but this does not display on D-Genies? I only see the regions that match 100% (which I also see on mummer, using either -q or -r)

Is there a way to get around this on D-genies?

**Comment by chklopp** [comment]
Minimap2 filters secondary alignments using the -p parameter value (-p FLOAT     min secondary-to-primary score ratio [0.8]). 
You either can install D-Genies locally and add the -p parameter to the command_line property in dgenies-master/tools.yaml or dgenies-master/win32/data/tools.yaml or run minimap2 locally with modified -p parameter and upload the paf file to http://dgenies.toulouse.inra.fr/ .
