### ISSUE TITLE
How long will the web service be restored

### ISSUE THREAD

**Issue by bismarck1008** [genotoul-bioinfo/dgenies#96]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**
 - OS: [e.g. linux, windows]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 50]

**Additional context**

**Comment by pbordron** [comment]
Hi bismarck1008,

There is a failure on storage where dgenies is hosted. Dgenies wont be online again before next week.

However, you can install dgenies on your own computer. The easy way is to install it with conda on linux or OSX. If you use windows, you can use [wsl](https://learn.microsoft.com/en-us/windows/wsl/install) to install the linux version.

**Comment by pbordron** [comment]
Look at #98 if dgenies fails with conda

**Comment by pbordron** [comment]
Please look at https://dgenies.toulouse.inra.fr/ to get update on service status

**Comment by pbordron** [comment]
A current firewall issue blocks access to dgenies website. Dgenies will be put back inline ASAP it is resolved

**Comment by pbordron** [comment]
Dgenies is back online
